itask/config/routes.rb
Itask::Application.routes.draw do  
  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "events#index"
  match 'manage', :to => 'manage#index'
  match 'attachments/download/:id/:filename', :controller => 'attachments', :action => 'download', :id => /\d+/, :filename => /.*/, :via => :get
  match 'attachments/download/:id', :controller => 'attachments', :action => 'download', :id => /\d+/, :via => :get
  
  match 'my/assignments_finished',:controller =>'my',:action =>'assignments_finished',:as=>'my_assignments_finished'
  match 'my/assignments_unfinished',:controller =>'my',:action =>'assignments_unfinished',:as=>'my_assignments_unfinished'

  resources :events
  resources :users do
    member do
      get 'assignments'
      get 'courses'
    end
  end

  resources :course_years do
    member do
      get 'apply'
      get 'manage'

    end
     resources :assignments do
     member do
       get 'unfinished'
    end
  end
       resources :assistants
  end
  resources :user_course_years do
    member do
      get 'approve'
    end
  end
  resources :assignments do
 

     resources :student_course_assignments do
		 member do 
		  get 'grade'
		  put 'grade'

		end
	 end

  end
  resources :student_course_assignments 

  resources :attachments  do
      member do
        get 'download'
		get 'file'
      end
  end

  mount Ckeditor::Engine => "/ckeditor"

  match ':controller(/:action(/:id))(.:format)'
end

itask/app/views/layouts/_course_year_menu.html.erb
 <%= render_breadcrumb %>
<div class="page-header">
  <h1><%= @course_year.course.name %> <small>老师:<%= @course_year.course.user.name%></small></h1>
 </br>
<% if user_signed_in?  %>
   <%= link_to '申请加入该课程',apply_course_year_path(@course_year),:class => 'btn' if !@course_year.has_a_student(current_user.id)&& cannot?(:manage ,@course_year)&& !current_user.has_role?(:teacher)%>
<% end %>
</div>

<%= render_list :class => "nav nav-tabs" do |li|
     li << link_to( "课程首页", course_year_path(@course_year))
     li << link_to("作业", course_year_assignments_path(@course_year) ) 
     li << link_to("管理", manage_course_year_path(@course_year)) if can? :manage, @course_year            
end %>

itask/app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Mysse,Mytask</a>
          <div class="nav-collapse collapse">
           
<%= render_list :class => "nav" do |li|
     li << link_to( "动态", events_path)
     li << link_to("课程", course_years_path)
              
end %>

            <form class="navbar-form pull-right">
             
               <ul class="nav">
                 <% if !current_user %>
                    <li><%= link_to "登录", new_user_session_path%></li>
                <%else%>
                    <li style="padding-top:5px;"><%= image_tag current_user.gravatar_url(:rating => 'R', :secure => true,:size=>30),class:"img-rounded" %>  </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= current_user.name %> 
                      <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "我的主页",user_path(current_user)%></li>                       
                        <li><%= link_to "我的作业",my_assignments_finished_path%></li>
                        <li class="divider"></li>
                         <li><%= link_to "修改个人资料",edit_user_registration_path%></li>
                        <li><%= link_to "注销",destroy_user_session_path,:method => "delete"%></li>

                      </ul>
                   </li>
                  
                <%end%>
              </ul>
             <!--  <input class="span2" type="text" placeholder="学号/工号">
              <input class="span2" type="password" placeholder="密码">
              <button type="submit" class="btn">登录</button> -->
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
</div>

itask/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 	 <%= render 'layouts/header' %>
	<div class="container"> 
		   
			<% if flash[:success]%>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
			    <%= flash[:success] %>
			</div>  
			<%end%>
			<% if flash[:alert]%>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">×</button>
			    <%= flash[:alert] %>
			</div>  
			<%end%> 
		   
<%= yield %>  

</div>

</body>
</html>

itask/app/views/layouts/no_auth_worong.html.erb
<%= render 'layout/header'%>