itask/config/routes.rb
Itask::Application.routes.draw do  
  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "events#index"
  match 'manage', :to => 'manage#index'
  match 'attachments/download/:id/:filename', :controller => 'attachments', :action => 'download', :id => /\d+/, :filename => /.*/, :via => :get
  match 'attachments/download/:id', :controller => 'attachments', :action => 'download', :id => /\d+/, :via => :get
  
  match 'my/assignments_finished',:controller =>'my',:action =>'assignments_finished',:as=>'my_assignments_finished'
  match 'my/assignments_unfinished',:controller =>'my',:action =>'assignments_unfinished',:as=>'my_assignments_unfinished'

  resources :events
  resources :users do
    member do
      get 'assignments'
      get 'courses'
    end
  end

  resources :course_years do
    member do
      get 'apply'
      get 'manage'

    end
     resources :assignments do
     member do
       get 'unfinished'
    end
  end
       resources :assistants
  end
  resources :user_course_years do
    member do
      get 'approve'
    end
  end
  resources :assignments do
 

     resources :student_course_assignments do
		 member do 
		  get 'grade'
		  put 'grade'

		end
	 end

  end
  resources :student_course_assignments 

  resources :attachments  do
      member do
        get 'download'
		get 'file'
      end
  end

  mount Ckeditor::Engine => "/ckeditor"

  match ':controller(/:action(/:id))(.:format)'
end

itask/app/models/course_year.rb
class CourseYear < ActiveRecord::Base
	resourcify
  attr_accessible :year, :semester, :course_id, :notice 
  belongs_to :course
  has_many   :assignments ,:dependent => :destroy
  has_many   :user_course_years
  has_many   :users, :through => :user_course_years
  has_many   :assistants
  validates :year , :format => { :with =>/[1-9]\d{3}-[1-9]\d{3}$/,:message =>"format should like 2012-2013" }
  validates :semester, :inclusion => { :in => %w(1 2),:message => "%{value} is not a valid semester" }

  def active_students
  	user_course_years = UserCourseYear.where(:course_year_id => self.id,:status => 1)
  	students = Array.new
  	user_course_years.each do |ucy|
  		students.push(ucy.user)
  	end
  	students
  end
  def add_a_assistant(user)
  	
  	if Assistant.where(:user_id => user.id).first
  		return false
  	else
  		assistant = Assistant.new
  	    assistant.course_year = self
  		assistant.user = user
  		user.add_role :TA
  		assistant.save
  	end

  end
  def has_a_student(student_id)
  	!UserCourseYear.where(:user_id => student_id,:course_year_id => self.id).blank?
  end
end

itask/app/controllers/course_years_controller.rb
class CourseYearsController < ApplicationController
  before_filter :find_course_year_by_id ,:except => :index
  before_filter :initialize_breadcrumb ,:except => :index
  load_and_authorize_resource


  def index
    @course_years = CourseYear.where(:year => params[:year]||"2012-2013",:semester => params[:semester]||"1");   
  end
  def edit

  end
  def show
    
  end
  def manage
    @course_year = CourseYear.find(params[:id])
    @user_course_years = @course_year.user_course_years.paginate(:page => params[:page],:per_page=>10)
    @assistants =  @course_year.assistants.paginate(:page => params[:page],:per_page=>10)
  end


  def apply

    current_user.apply_for_course(params[:id])
    redirect_to course_year_path(@course_year)
  end
  def remove_student

    current_user.remove_from_course_year(params[:id])
    redirect_to course_year_path(@course_year)
  end
  def approve_application

    current_user.attend_to_course(params[:id])
    redirect_to course_year_path(@course_year)
  end
  def update
  	@course_year = CourseYear.find(params[:id])

    respond_to do |format|

      if @course_year.update_attributes(params[:course_year])
        format.html { redirect_to course_year_path(@course_year), notice: 'Notice was successfully updated.' }

        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course_year.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def find_course_year_by_id
    @course_year = CourseYear.find(params[:id])
  end
  
  def initialize_breadcrumb

    drop_breadcrumb("Courses", course_years_path)
    drop_breadcrumb(@course_year.course.name)

  end
end

itask/app/helpers/course_years_helper.rb
module CourseYearsHelper
end

itask/app/views/course_years/edit.html.erb
<%= form_for(@course_year) do |f| %>
  <% if @course_year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_year.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course_year.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notice %><br />
    <%= f.text_field :notice %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', course_year_assignments_path(@course_year) %>

itask/app/views/course_years/index.html.erb
<html>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span9 hero-unit">
     <h1> 课程列表 </h1>
<table class="table table-hover table-striped">
	  <thead>  
	<tr>
		<th> 学年 学期 </th> 
		<th> 课程序号 </th> 
		<th> 课程名称 </th>
		<th> 任课教师 </th>
	</tr>
	  </thead>                       
	<tbody>
	<% @course_years.each do |c| %>
	<tr>
		<td><%= c.year %> <%= c.semester %></td>
		<td><%= c.course.course_num %></td>
		<td><%= c.course.name %></td>
		<td><%= c.course.user.name %></td>
		<td><%= link_to "View" , course_year_path(c) %></td>
<!-- 		<% if can? :destroy, c %>
  			<td><%= link_to "delete", course_year_path(c),:method=>"delete" %></td>
		<% end %> -->
	</tr>
	<% end %>  
	</tbody>
</table>
    </div>
    <div class="span3 hero-unit">
      <!--Body content-->
    </div>
  </div>
</div>


</html>
	

itask/app/views/course_years/manage.html.erb
<%= render "layouts/course_year_menu"%>
<div class="container-fluid">
  <div class="row-fluid">
<div class="span8 hero-unit">
	<div class="page-header">
  <h4>选课学生<span class="divider"></h4>
</div>
	<table  class="table table-hover table-striped">                        
	<thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>状态</th>
                  <th>操作</th>
                </tr>
  </thead> 
  <tbody> 
   <% @user_course_years.each do |uc| %>     
	<tr>  
		<td><%= uc.user.user_num %></td> 
		<td><%= uc.user.name %></td>
		<td><% if uc.status == 1%>
			<span class="badge badge-success">通过</span>
			
			<% elsif uc.status == 0%>

			<span class="badge badge-important">待审核</span>



			<%end%>
		</td> 
         <td>
         	<% if uc.status == 0%>
         	<%= link_to "批准",approve_user_course_year_path(uc)%>
               <%= link_to "不批准",user_course_year_path(uc),:method => 'delete'%> </td>
            <%elsif uc.status == 1%>
               <%= link_to "移除",user_course_year_path(uc),:method => 'delete'%> </td>
            <%end%>

	</tr> 
	<%end%>   
	</tbody>
</table>
<%= will_paginate @user_course_years %> 
<div>
<span><label>添加学生</label>
    <%= form_tag user_course_years_path,:method => "post" do %>
	<%= text_field_tag :user_num%>
	<%= hidden_field_tag "course_year_id",@course_year.id %>
	<%= submit_tag "添加"%>
	<%end%></span>
	</div>
</div>
<div class="span4 hero-unit">
<div class="page-header">
  <h4>助教<span class="divider"></h4>
</div>
		<table  class="table table-hover table-striped">                        
	<thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>
                  
                  <th>操作</th>
                </tr>
  </thead> 
  <tbody> 
   <% @assistants.each do |a| %>     
	<tr>  
		<td><%= a.user.user_num %></td> 
		<td><%= a.user.name %></td>		
         <td><%= link_to "移除",course_year_assistant_path(@course_year,a),:method => "delete"%></td>
	</tr> 
	<%end%>   
	</tbody>
</table>
<%= will_paginate @assistants %> 
	<p>添加助教</p>
    <%= form_tag course_year_assistants_path(@course_year),:method => "post" do %>
	<%= text_field_tag :user_num%>
	<%= submit_tag "添加"%>
	<%end%>
	</div>
</div>
</div>

itask/app/views/course_years/show.html.erb
<%= render "layouts/course_year_menu"%>
<div class="hero-unit"><%= @course_year.notice %></div>
<br/>

<%= link_to '更新公告', edit_course_year_path(@course_year) ,class:"btn" if can? :manage,@course_year%> 