itask/config/routes.rb
Itask::Application.routes.draw do  
  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "events#index"
  match 'manage', :to => 'manage#index'
  match 'attachments/download/:id/:filename', :controller => 'attachments', :action => 'download', :id => /\d+/, :filename => /.*/, :via => :get
  match 'attachments/download/:id', :controller => 'attachments', :action => 'download', :id => /\d+/, :via => :get
  
  match 'my/assignments_finished',:controller =>'my',:action =>'assignments_finished',:as=>'my_assignments_finished'
  match 'my/assignments_unfinished',:controller =>'my',:action =>'assignments_unfinished',:as=>'my_assignments_unfinished'

  resources :events
  resources :users do
    member do
      get 'assignments'
      get 'courses'
    end
  end

  resources :course_years do
    member do
      get 'apply'
      get 'manage'

    end
     resources :assignments do
     member do
       get 'unfinished'
    end
  end
       resources :assistants
  end
  resources :user_course_years do
    member do
      get 'approve'
    end
  end
  resources :assignments do
 

     resources :student_course_assignments do
		 member do 
		  get 'grade'
		  put 'grade'

		end
	 end

  end
  resources :student_course_assignments 

  resources :attachments  do
      member do
        get 'download'
		get 'file'
      end
  end

  mount Ckeditor::Engine => "/ckeditor"

  match ':controller(/:action(/:id))(.:format)'
end

itask/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  resourcify
  attr_accessible :title, :desp, :end_time,:course_year_id,:user_id, :status
  has_many :student_course_assignments 
  has_many :events ,:dependent => :destroy
  belongs_to :course_year
  belongs_to :user
  
  validates_presence_of :title, :desp, :end_time
  validates :end_time, :format => { :with => /\A(1|2)\d{3}-(0|1)\d-\d{2}\z/, :message => "format should like 2012-01-01"}

  def unfinished_students

  	all_students = User.joins(:user_course_years => :course_year).where(:course_years =>{ :id => self.course_year_id},:user_course_years => {:status => 1})
    finish_students = finished_students
  
    if !finish_students.blank?
         all_students - finish_students
    else
         all_students
    end
    #all_students.where(:id => finish_student_ids).delete_all
  	# student_course_assignments = self.student_course_assignments
    # finish_students = Array.new

	  #   student_course_assignments.each do |sca|
	  #        finish_students.push(sca.user)
	  #   end

   #  students = self.course_year.active_students
   #  students - finish_students
  end

  def finished_students
     
      User.joins(:student_course_assignments => :assignment).where(:assignments => {:id => self.id}) 
     #    Assignment.joins(:student_course_assignments => :user).where(:student_course_assignments => {:user_id => self.id})    

     #    student_course_assignments = self.student_course_assignments
     #    finish_students = Array.new

	    # student_course_assignments.each do |sca|
	    #      finish_students.push(sca.user)
	    # end
	    # finish_students
  end
  def has_a_finished_student(user)
        student_course_assignments = self.student_course_assignments
        finish_students = Array.new

	    student_course_assignments.each do |sca|
	         finish_students.push(sca.user)
	    end
	    finish_students.include? user
  end



end

itask/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	before_filter :find_course_year_by_course_year_id
	before_filter :find_assignment_by_id,:only => [:show,:edit,:update,:unfinished]
	before_filter :initialize_breadcrumb ,:except => [:index,:new,:create]
	load_and_authorize_resource
	skip_authorize_resource :only => [:new,:create]

	def index
		#@courseyear = CourseYear.find(params[:course_year_id])
		@assignments = @course_year.assignments
		drop_breadcrumb("Courses", course_years_path)
    	drop_breadcrumb(@course_year.course.name)
	end
	
	def edit
	end

	def update
		@assignment = Assignment.find(params[:id])
		respond_to do |format|

      	if @assignment.update_attributes(params[:assignment])
          if @assignment.end_time > Time.now.to_date
            @assignment.status = 0
            @assignment.save
          end
        	format.html { redirect_to course_year_assignment_path(@assignment.course_year,@assignment), notice: 'Assignemnt was successfully updated.' }
        	format.json { head :no_content }
      	else
        	format.html { render action: "edit" }
        	format.json { render json: @assignment.errors, status: :unprocessable_entity }
      	end
    	end
	end
	
	def show_by_course
		@assignments = @course_year.assignments.paginate(:page => params[:page],:per_page=>10)
	end 
    def unfinished
    	@unfinish_students =  @assignment.unfinished_students.paginate(:page => params[:page],:per_page=>10)
    	 respond_to do |format|
        format.html {
        @sca = StudentCourseAssignment.new 
        @sca.attachments.build
        # @sca.attachments.build
        }
    end
    end
	def show
	
    
        @finish_student_course_assignments = @assignment.student_course_assignments.paginate(:page => params[:page],:per_page=>10)
        respond_to do |format|
        format.html {
        @sca = StudentCourseAssignment.new 
        @sca.attachments.build
        # @sca.attachments.build
        }
    end
	    
	end

	def new
		@assignment = Assignment.new
		drop_breadcrumb("Courses", course_years_path)
    	drop_breadcrumb(@course_year.course.name,course_year_path(@course_year))
    	drop_breadcrumb("New Assignment")
			
	end

	def create
		 @assignment = Assignment.new(params[:assignment])
		 @assignment.status = 0
		 @assignment.course_year = @course_year
        
        if current_user
			@assignment.user = current_user
		end
		respond_to do |format|
      	if @assignment.save
      		add_event_info(@assignment,'create assignment',@assignment)
        	format.html { redirect_to course_year_assignment_path(@course_year,@assignment), notice: 'Assignment was successfully created.' }
        	format.json { render json: @assignment, status: :created, location: @assignment }
      	else
        	format.html { render action: "new", notice: 'Imporper attributes' }
        	format.json { render json: @assignment.errors, status: :unprocessable_entity }
      	end
    end

	end
	def find_assignment_by_id
		@assignment = Assignment.find(params[:id])

	end
  	def initialize_breadcrumb
     	drop_breadcrumb("Courses", course_years_path)
    	drop_breadcrumb(@course_year.course.name,course_year_path(@course_year))
        drop_breadcrumb(@assignment.title)
  	end
end

itask/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

itask/app/views/assignments/edit.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this Assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<h1>Edit assignment</h1>

<%= form_for @assignment,:url => course_year_assignment_path(@assignment.course_year,@assignment) do |f| %>

  <div class="field">
    <%= f.label :作业标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :作业描述 %><br />
    <%= f.cktext_area :desp %>
  </div>
  <div class="field">
    <%= f.label :截止时间 %><br />
    <%= f.text_field :end_time, 'data-behaviour' => 'datepicker' %>
  </div>
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

<%= link_to 'Back', course_year_assignment_path(@assignment.course_year,@assignment) %>

itask/app/views/assignments/index.html.erb
<%= render "layouts/course_year_menu" %>
<table  class="table table-hover table-striped">                        
	<thead>
                <tr>
                  <th>作业标题</th>
                  <th>作业描述</th>
                  <th>添加者</th>
                  <th>操作</th> 

                </tr>
  </thead> 
  <tbody> 
	<% @assignments.each do |a| %>     
	<tr>  
		<td><%= a.title %></td> 
		<td><%= raw a.desp %></td> 
		<td><%= a.user.name %></td> 
		<td><%= link_to "view details" ,course_year_assignment_path(@course_year,a)%></td> 
	</tr> 
	<%end%>   
	</tbody>
</table>
<% if can?(:manage,@course_year)%>
<%= link_to '新建作业', new_course_year_assignment_path(@course_year) ,class:"btn"%>

<% end %>

itask/app/views/assignments/new.html.erb
<%= render "layouts/course_year_menu"%>
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this Assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<h1>New assignment</h1>

<%= form_for @assignment,:url => course_year_assignments_path do |f| %>

  <div class="field">
    <%= f.label :作业标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :作业描述 %><br />
    <%= f.cktext_area :desp %>
  </div>
  <div class="field">
    <%= f.label :截止时间 %><br />
    <%= f.text_field :end_time, 'data-behaviour' => 'datepicker' %>
  </div>
  <div class="actions">
    <%= f.submit "Create"%>
  </div>
<% end %>

itask/app/views/assignments/show.html.erb
<%= render "layouts/course_year_menu"%>
<div class="hero-unit">
<h2><%=  @assignment.title %></h2>
<p>作业描述:<%=  raw @assignment.desp %></p>


<div class="contextual">
	<% if user_signed_in? %>
<%= link_to "更新作业", edit_course_year_assignment_path(@assignment.course_year,@assignment),class:"btn" if can? :manage,@assignment %>
<%= link_to("上传作业",
            new_assignment_student_course_assignment_path(@assignment), :class=>"btn",
            :onclick => 'showAndScrollTo("add-studnet-assignment", "add-studnet-assignment"); return false;') if @assignment&& current_user.has_a_course_year(@assignment.course_year) %>
            <% end%>
</div>

<div id="add-studnet-assignment" class="hero-unit" style="display:none;">
<h2><%= "上传作业"%></h2>

<%= form_for @sca, :url => assignment_student_course_assignments_path(@assignment),
                                           :html => { :id => 'student-assignment-form', :multipart => true } do |f| %>
<%= render :partial => 'student_course_assignments/form', :locals => { :f => f } %>
<%= submit_tag "上传" ,:class => "btn" %>

<%= link_to "取消", "#", :onclick => '$("#add-studnet-assignment").hide()' %>
<% end%>
</div>
</div>
<%= render_list :class => "nav nav-tabs" do |li|
     li << link_to( "已上交", course_year_assignment_path(@assignment.course_year,@assignment))
     li << link_to("未上交", unfinished_course_year_assignment_path(@assignment.course_year,@assignment) ) 
end %>
<%= render :partial=> 'student_course_assignments/student_assignments',
:locals => { :studentCourseAssignments => @finish_student_course_assignments } %>
<%= will_paginate @finish_student_course_assignments %> 





itask/app/views/assignments/unfinished.html.erb
<%= render "layouts/course_year_menu"%>
<div class="hero-unit">
<h2><%=  @assignment.title %></h2>
<p>作业描述:<%=  raw @assignment.desp %></p>


<div class="contextual">
	<% if user_signed_in? %>
<%= link_to("上传作业",
            new_assignment_student_course_assignment_path(@assignment), :class=>"btn",
            :onclick => 'showAndScrollTo("add-studnet-assignment", "add-studnet-assignment"); return false;') if @assignment&& current_user.has_a_course_year(@assignment.course_year) %>
            <% end%>
</div>

<div id="add-studnet-assignment" class="hero-unit" style="display:none;">
<h2><%= "上传作业"%></h2>

<%= form_for @sca, :url => assignment_student_course_assignments_path(@assignment),
                                           :html => { :id => 'student-assignment-form', :multipart => true } do |f| %>
<%= render :partial => 'student_course_assignments/form', :locals => { :f => f } %>
<%= submit_tag "上传" ,:class => "btn" %>

<%= link_to "取消", "#", :onclick => '$("#add-studnet-assignment").hide()' %>
<% end%>
</div>
</div>
<%= render_list :class => "nav nav-tabs" do |li|
     li << link_to( "已上交", course_year_assignment_path(@assignment.course_year,@assignment))
     li << link_to("未上交", unfinished_course_year_assignment_path(@assignment.course_year,@assignment) ) 
end %>

<h3>未上交</h3>
<table  class="table table-hover table-striped">                        
	<thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>                
                </tr>
  </thead> 
  <tbody> 
  	
   <% @unfinish_students.each do |us| %>     
	<tr>  
		<td><%= us.user_num %></td> 
		<td><%= us.name %></td>
		
	</tr> 
	<%end%>   
	</tbody>
</table>
<%= will_paginate @unfinish_students %> 