itask/config/routes.rb
Itask::Application.routes.draw do  
  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "events#index"
  match 'manage', :to => 'manage#index'
  match 'attachments/download/:id/:filename', :controller => 'attachments', :action => 'download', :id => /\d+/, :filename => /.*/, :via => :get
  match 'attachments/download/:id', :controller => 'attachments', :action => 'download', :id => /\d+/, :via => :get
  
  match 'my/assignments_finished',:controller =>'my',:action =>'assignments_finished',:as=>'my_assignments_finished'
  match 'my/assignments_unfinished',:controller =>'my',:action =>'assignments_unfinished',:as=>'my_assignments_unfinished'

  resources :events
  resources :users do
    member do
      get 'assignments'
      get 'courses'
    end
  end

  resources :course_years do
    member do
      get 'apply'
      get 'manage'

    end
     resources :assignments do
     member do
       get 'unfinished'
    end
  end
       resources :assistants
  end
  resources :user_course_years do
    member do
      get 'approve'
    end
  end
  resources :assignments do
 

     resources :student_course_assignments do
		 member do 
		  get 'grade'
		  put 'grade'

		end
	 end

  end
  resources :student_course_assignments 

  resources :attachments  do
      member do
        get 'download'
		get 'file'
      end
  end

  mount Ckeditor::Engine => "/ckeditor"

  match ':controller(/:action(/:id))(.:format)'
end

itask/app/models/student_course_assignment.rb
class StudentCourseAssignment < ActiveRecord::Base
  attr_accessible :score, :comment, :finish_status,:attachments, :attachments_attributes
  has_many :attachments ,:as => :attachmentable,:dependent => :destroy
  belongs_to :assignment
  belongs_to :user
  accepts_nested_attributes_for :attachments
 

end

itask/app/controllers/student_course_assignments_controller.rb
class StudentCourseAssignmentsController < ApplicationController
	load_and_authorize_resource :except=>:new
    
    def index
    	@scas = StudentCourseAssignment.all.paginate(:page => params[:page],:per_page=>10)
    end

	def new
		@sca = StudentCourseAssignment.new
		@sca.attachments.build

	end
	def create
		@assignment = Assignment.find(params[:assignment_id])
		if  !StudentCourseAssignment.where("user_id=? and assignment_id = ?",current_user.id,@assignment.id).blank?
			flash[:alert] = "you have uploaded "		
			redirect_to course_year_assignment_path(@assignment.course_year,@assignment)
			return
	    end
		@sca = StudentCourseAssignment.new(params[:student_course_assignment])
		
		@sca.user = current_user
		@sca.assignment = @assignment
		@sca.finish_status = 0
		if @sca.save
			flash[:alert] = "success"
			redirect_to course_year_assignment_path(@assignment.course_year,@assignment)
		else
			flash[:alert] = "fail"
			redirect_to course_year_assignment_path(@assignment.course_year,@assignment)
		end
        
	end
    def destroy
    	
    	@sca = StudentCourseAssignment.find(params[:id])
    	@assignment = @sca.assignment
    	@course_year = @sca.assignment.course_year
    	@sca.attachments do |a|
    		a.user_upload = nil
    		a.save
    	end
    	@sca.save
    	if @sca.destroy
    		flash[:alert] = "success"
    	end
    	redirect_to course_year_assignment_path(@course_year,@assignment)
    end
	
	def grade
	if request.put?
	     @sca = StudentCourseAssignment.update(params[:id],:score=>params[:student_course_assignment][:score],:comment=>params[:student_course_assignment][:comment])
		 
		 @assignment = Assignment.find(params[:assignment_id])
		 if @sca.save
			flash[:alert] = "successfully"
			redirect_to course_year_assignment_path(@assignment.course_year,@assignment)
		 else
		     flash[:alert] = "fail!"
			 redirect_to course_year_assignment_path(@assignment.course_year,@assignment)
		 end

	   
		
	else
		 @sca = StudentCourseAssignment.find(params[:id])
		 @assignment = Assignment.find(params[:assignment_id])
		 
	end
	end
		
end

itask/app/helpers/student_course_assignments_helper.rb
module StudentCourseAssignmentsHelper
end

itask/app/views/student_course_assignments/_form.html.erb
<%= render :partial => 'attachments/form', :locals => { :f => f } %>

itask/app/views/student_course_assignments/_student_assignments.html.erb



﻿<table  class="table table-hover table-striped">                        
	<thead>
                <tr>
                  <th>学生</th>
                  <th>上交时间</th>
                  <th>附件名称</th>
                  <% if @assignment.status == 1%>

                   <th>分数</th>
                   <%end%>
                  <th>操作</th> 

                </tr>
  </thead> 
  <tbody> 
	<% studentCourseAssignments.each do |sta| %>     
	<tr>  
		<td><% if !sta.blank? %>
			<% if !sta.user.blank?%>
			    <%= sta.user.name %>
			    <%end%>
		   <%end%>
		</td> 
		<td><%=sta.created_at%></td> 
		<th><% if !sta.attachments.blank? %>
			    <% sta.attachments.each do |a| %>
			    	<% if sta.assignment.status == 1||can?(:manage,@assignment)  %>
			    	<%= link_to_attachment a ,:download=>true %>
			    	<% else %>
			    	<%= a.user_upload_file_name%>
			    	<% end %>
			    <%end%>
		   <%end%></th>
		<% if @assignment.status == 1%>
			<td><%=sta.score%></td>
				<%end %> 
		<td>
			
		
		 <% sta.attachments.each do |a| %>
		 
			<%= link_to "查看包", attachment_path(a), :target => "_blank" if sta.assignment.status == 1||can?(:manage,@assignment) %>
		 <%end%>

		    <%= link_to "抄袭检测", :controller => "cheatcheck", :action => "checkresult", :id => sta if can?(:manage,@assignment) if can?(:grade,sta)%>
			<%= link_to "评分", grade_assignment_student_course_assignment_path(@assignment,sta), :target => "_blank" if can?(:grade,sta)%>
			<%= link_to "删除", student_course_assignment_path(sta),:method => "delete" if can?(:destroy,sta)%>			
			
		</td> 
					
	</tr> 
	<%end%>   
	</tbody>

</table>

itask/app/views/student_course_assignments/grade.html.erb
<p>please grade<p>
<%= form_for @sca, :url => grade_assignment_student_course_assignment_path(@assignment,@sca) do |f| %>

  <div class="field">
    <%= f.label :score %>
    <%= f.text_field :score %>
  </div>
  
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  
  <div class="actions">
    <%= f.submit "OK!"%>
  </div>
<% end %>

itask/app/views/student_course_assignments/index.html.erb
<h1><%= @sca.score %><h1>

itask/app/views/student_course_assignments/new.html.erb
<%= form_for @sca, :url => assignment_student_course_assignments_path,:html => { :multipart => true } do |form| %>
   
    
  <%= form.submit "Create"%>
<% end %>  

itask/app/views/student_course_assignments/show.html.erb
<%= @sca.score %>
<%= @sca.comment %>